### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by jdrew82** [networktocode/netutils#61]
### Environment
* Python version:  3.7.9
* netutils version:  1.1.3

### Expected Behavior
Configuration is parsed without IndexError being thrown.

### Observed Behavior
Run a ConfigCompliance job from `nautobot-plugin-golden-config` and get the following error:

```
celery_1    | 15:44:21.188 ERROR   nautobot.jobs.ComplianceJob :
celery_1    |   RENDER COMPLIANCE TASK GROUP failed: list index out of range
celery_1    | [2021-10-06 15:44:21,188: ERROR/ForkPoolWorker-1] RENDER COMPLIANCE TASK GROUP failed: list index out of range
celery_1    | [2021-10-06 15:44:21,188: ERROR/ForkPoolWorker-1] example_host | RENDER COMPLIANCE TASK GROUP failed: list index out of range
celery_1    | [2021-10-06 15:44:21,203: ERROR/ForkPoolWorker-1] Host 'example_host': task 'RENDER COMPLIANCE TASK GROUP' failed with traceback:
celery_1    | Traceback (most recent call last):
celery_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 589, in update_or_create
celery_1    |     obj = self.select_for_update().get(**kwargs)
celery_1    |   File "/usr/local/lib/python3.7/site-packages/cacheops/query.py", line 353, in get
celery_1    |     return qs._no_monkey.get(qs, *args, **kwargs)
celery_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 431, in get
celery_1    |     self.model._meta.object_name
celery_1    | nautobot_golden_config.models.ConfigCompliance.DoesNotExist: ConfigCompliance matching query does not exist.
celery_1    |
celery_1    | During handling of the above exception, another exception occurred:
celery_1    |
celery_1    | Traceback (most recent call last):
celery_1    |   File "/usr/local/lib/python3.7/site-packages/nornir/core/task.py", line 99, in start
celery_1    |     r = self.task(self, **self.params)
celery_1    |   File "/usr/local/lib/python3.7/site-packages/nautobot_golden_config/nornir_plays/config_compliance.py", line 116, in run_compliance
celery_1    |     "extra": "",
celery_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/models/manager.py", line 85, in manager_method
celery_1    |     return getattr(self.get_queryset(), name)(*args, **kwargs)
celery_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 594, in update_or_create
celery_1    |     obj, created = self._create_object_from_params(kwargs, params, lock=True)
celery_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 610, in _create_object_from_params
celery_1    |     obj = self.create(**params)
celery_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 447, in create
celery_1    |     obj.save(force_insert=True, using=self.db)
celery_1    |   File "/usr/local/lib/python3.7/site-packages/nautobot_golden_config/models.py", line 223, in save
celery_1    |     value = feature_compliance(feature, self.actual, self.intended, get_platform(self.device.platform.slug))
celery_1    |   File "/usr/local/lib/python3.7/site-packages/netutils/config/compliance.py", line 322, in feature_compliance
celery_1    |     feature_data.update(_check_configs_differences(intended_cfg, backup_cfg, network_os))
celery_1    |   File "/usr/local/lib/python3.7/site-packages/netutils/config/compliance.py", line 57, in _check_configs_differences
celery_1    |     missing = diff_network_config(intended_cfg, actual_cfg, network_os)
celery_1    |   File "/usr/local/lib/python3.7/site-packages/netutils/config/compliance.py", line 256, in diff_network_config
celery_1    |     compare_parser = os_parser(compare_config)
celery_1    |   File "/usr/local/lib/python3.7/site-packages/netutils/config/parser.py", line 492, in __init__
celery_1    |     super(IOSConfigParser, self).__init__(config)
celery_1    |   File "/usr/local/lib/python3.7/site-packages/netutils/config/parser.py", line 429, in __init__
celery_1    |     super(CiscoConfigParser, self).__init__(config)
celery_1    |   File "/usr/local/lib/python3.7/site-packages/netutils/config/parser.py", line 47, in __init__
celery_1    |     super(BaseSpaceConfigParser, self).__init__(config)
celery_1    |   File "/usr/local/lib/python3.7/site-packages/netutils/config/parser.py", line 27, in __init__
celery_1    |     self.build_config_relationship()
celery_1    |   File "/usr/local/lib/python3.7/site-packages/netutils/config/parser.py", line 564, in build_config_relationship
celery_1    |     self._update_same_line_children_configs()
celery_1    |   File "/usr/local/lib/python3.7/site-packages/netutils/config/parser.py", line 516, in _update_same_line_children_configs
celery_1    |     previous_line = new_config_lines[-1]
celery_1    | IndexError: list index out of range
```

### Steps to Reproduce
1. Setup Nautobot and Nautobot Golden Config plugin.
2. Run compliance job.
3. Randomly appear to get IndexError.

**Comment by jdrew82** [comment]
Re-opening as I am able to reproduce this repeatedly now without fail. I was incorrect in my original post that it's random. It appears to be related to the compliance job but only when it's run as part of a bulk job, ie when you run the Job that does all compliance tasks together. The device backup and intended generation work but the compliance job fails with the `list index out of range` error.

**Comment by jdrew82** [comment]
This has been confirmed to be related to duplicate lines in the configuration. This can be considered resolved as we don't want to change the code to ignore duplicate lines.

**Comment by dgarros** [comment]
It feels like we shouldn't raise an exception especially if we know what is the issue, without changing the code too much how can we handle that better ?

**Comment by itdependsnetworks** [comment]
I think the point is, this is related to #1
